Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -27,15 +27,13 @@ jobs:
         run: |
           echo "Starting Catalog json Generation"
           /usr/local/bin/catalog_update update --path "${PWD}"
-          pwd
-          ls -la
-          git config user.name "TrueCharts-Bot"
-          git config user.email "bot@truecharts.org"
-          git add catalog.json || echo "Adding catalog.json failed"
-          git commit -m "Commit catalog.json" || echo "Commiting catalog.json failed"
 
       - name: Merge staging into main
         run: |
           git config user.name "TrueCharts-Bot"
           git config user.email "bot@truecharts.org"
+          git config user.name "TrueCharts-Bot"
+          git config user.email "bot@truecharts.org"
+          # git add catalog.json || echo "Adding catalog.json failed"
+          # git commit -m "Commit catalog.json" || echo "Commiting catalog.json failed"
           git push -f origin staging:main
